# general configuration
debug: true
version: 0.1

project: atnls

base_url: /
ajaxPath: /q                    # path added to the url to get ajax templates

# folders
twigs: /twigs                   # main twigs folder
log: /log.log                   # use 'false' to disable logger

# REQUIRED # import as it generates the routing system and the seo contents
    # the data uses this structure: https://docs.google.com/spreadsheet/ccc?key=0AtJGbTMFIBvQdDJKMzhmMHVZNGRhYmNSc2FyYWZTTlE&usp=sharing
routing:
#  url: ./dataOK/routing.csv     # url local o remota (mejor no)
  url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRiB6d8luekEBXk3nYSsCaDMUxmx4Xio5dP2Qu_K3JAlCI_-Gb_UWGXII2DFp9OG6kMh7w3cB_7Vfol/pub?gid=0&single=true&output=csv
  format: csv                   # csv o json
  initialRoute: home            # nombre de ruta de la home
  indexColumn: name             # genera el indice a partir de esta columna
  exposeTWIG: true              # pasa estos datos al js y a las plantillas
  exposeJS: false

  # autload de plantillass
autoloader:
  autoload: /twigs/autoload

dataImports:
  # diccionario:
  #   url: ./dataOK/diccionario.csv
  #   format: csv
  #   exposeTWIG: true
  #   exposeTWIG: true

rawData: # plain data imported in the templates
  audioPath: 'img/'
  poemasUrl: 'poemas/'
  poetasUrl: 'poetas/'
  ajaxUrl: 'ajax/'
  ajaxRedes: 'dataOK/redes.json'
  hash: 'memoriadefuturo'
  poemas:
    bajo-una-lluvia-fria-de-poligono: 'Bajo Una Lluvia Fria De Poligono'
    cabo-sounion: 'Cabo Sounion'
    cancion-asesinato: 'Canción Asesinato'
    completamente-viernes: 'Completamente Viernes'
    cuarentena: 'Cuarentena'
    el-amor: 'El Amor'
    el-insomnio-de-jovellanos: 'El Insomnio De Jovellanos'
    fotografias-veladas-de-la-lluvia: 'Fotografias Veladas De La Lluvia'
    la-inmortalidad: 'La Inmortalidad'
    life-vest-under-your-seat: 'Life Vest Under Your Seat'
    recuerda-que-tu-existes: 'Recuerda Que Tu Existes'
  poetas:
    marwan: 'Marwan'
    elvira-sastre: 'Elvira Sastre'
    carlos-prado: 'Carlos Prado'
    guille-galvan: 'Guille Galván'
    escandar-algeet: 'Escandar Algeet'
    luis-garcia-montero: 'Luis García Montero'